apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-client-app-deployment
  namespace: productapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-client-app
  template:
    metadata:
      labels:
        app: product-client-app
    spec:
      containers:
      - name: product-client-app
        image: jovan141/product-front:latest
        ports:
        - containerPort: 80
