apiVersion: v1
kind: Service
metadata:
  name: product-client-app-service
  namespace: productapp
spec:
  selector:
    app: product-client-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
