apiVersion: v1
kind: ConfigMap
metadata:
  name: productapi-config
  namespace: productapp
data:
  APPSETTINGS_JSON: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "MongoDBSettings": {
        "ConnectionString": "mongodb://mongo:27017",
        "DatabaseName": "ProductDb"
      }
    }
