apiVersion: v1
kind: Service
metadata:
  name: productapi-service
  namespace: productapp
spec:
  selector:
    app: productapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
